FROM ghcr.io/mlflow/mlflow:v2.17.0

WORKDIR /mlflow

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri sqlite:////mlflow/mlflow.db \
    --default-artifact-root /mlflow/artifacts