version: "3.9"

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    container_name: mlflow-server

    ports:
      - "5000:5000"

    volumes:
      - ./mlruns:/mlruns
      - mlflow-data:/mlflow

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
       --default-artifact-root ./mlruns
      --workers 2

    restart: unless-stopped

  ragops-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ragops-api

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - chroma-db:/app/db

    environment:
      HF_TOKEN: ${HF_TOKEN}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: ragops-ai
      RESUME_PATH: /app/data/Rahul_Shewatkar_Resume.pdf
      CHROMA_DB_DIR: /app/db
      ANONYMIZED_TELEMETRY: "False"
      CHROMA_TELEMETRY: "False"
      GIT_PYTHON_REFRESH: quiet

    depends_on:
      - mlflow

    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml


    depends_on:
      - ragops-api

    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus

    restart: unless-stopped

volumes:
  mlflow-data:
  chroma-db:
  grafana-data:

