FROM python:3.10-slim

WORKDIR /app

RUN pip install mlflow==2.17.0 psycopg2-binary

EXPOSE 5000

CMD mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri sqlite:///mlflow.db \
    --default-artifact-root ./artifacts